export function GET() {
    return Response.json({ message: 'Accediste a una API' })
}

//SE USARA PARA GESTIONAR CUALQUIER SOLICITUD DE POST EN API/AUTH
//POR EJEMPLO: REGISTRAR UN USUARIO 

export function POST(){

    //1. OBTENER EL CORREO Y CONTRASEÑA DESDE LA REQ DEL BODY.

    //2. CREAR LA CONEXIÒN CON LA BASE DE DATOS.

    //3. CONSULTAR A LA BASE DE DATOS SI EL USUARIO EXISTE

    //4.a) SI EL USUARIO EXISTE, CREO LA SESIÓN.
    //4.b) SI EL USUARIO NON EXISTE, CREO UN NUEVO USUARIO Y UNA SESIÓN.

    //5. RETORNO EL TOKEN DE LA SESIÓN

}